"""Extract and verify the runtime data required by supported hardware.

Speaker tuning is searched for in every vendor cabinet of the restore tool, so
supporting another laptop needs no change here: the cabinets and their device
files are discovered, and the matching table is generated from what was found.
Files listed in runtime-sha256.json are verified against it.
"""
import hashlib
import io
import json
from pathlib import Path
import re
import shutil
import struct
import subprocess
import sys
import tempfile
import zipfile

# Global settings and audio profiles come from the first cabinet that has them,
# so the generic one is preferred over a vendor copy of the same files.
PREFERRED = re.compile(r'CNXT|Generic', re.IGNORECASE)
# Device tuning is named after the subsystem it belongs to, for example
# 146213C0_InternalSpeakers.nsx or 1D05E022_Speakers.nsx.
SUBSYSTEM = re.compile(r'^([0-9A-Fa-f]{6,8})[_-]')
AUTO_TABLE = 'Devices.auto.json'


def settings_archives(path):
    """Read every vendor settings cabinet out of the restore tool payload."""
    data = Path(path).read_bytes()
    start = data.find(b"PK\x03\x04")
    end = data.find(b"PK\x05\x06", start)
    if start < 0 or end < 0:
        raise ValueError("Runtime settings archive is absent")
    comment = struct.unpack_from("<H", data, end + 20)[0]
    with zipfile.ZipFile(io.BytesIO(data[start:end + 22 + comment])) as bundle:
        cabinets = [name for name in bundle.namelist()
                    if name.lower().endswith('.cab') and name.lower().startswith('drivers\\ext\\')]
        return [(name, bundle.read(name)) for name in cabinets]


def ordered(cabinets):
    """Sort so that generic cabinets come first, then by vendor path."""
    return sorted(cabinets, key=lambda item: (0 if PREFERRED.search(item[0]) else 1, item[0]))


def unpack(cabinet, destination):
    """Extract one cabinet, returning True when it held anything."""
    root = Path(destination)
    root.mkdir(parents=True, exist_ok=True)
    before = len(list(root.rglob('*')))
    subprocess.run(["cabextract", "-q", "-d", str(root), str(cabinet)], check=True)
    return len(list(root.rglob('*'))) != before


def device_table(tuning, output, origin):
    """Write the generated hardware table for the tuning files that were found."""
    devices, seen = [], set()
    for path in sorted(Path(tuning).glob("*.nsx")):
        match = SUBSYSTEM.match(path.name)
        if match is None or match.group(1).lower() in seen:
            continue
        seen.add(match.group(1).lower())
        devices.append({
            "name": path.stem.replace("_", " "),
            "subsystem": match.group(1).lower(),
            "device_file": f"Devices/{path.name}",
            "verified": False,
        })
    if not devices:
        return 0
    table = {
        "_comment": "Generated by packaging/extract_runtime.py from the vendor cabinets of the "
                   "Nahimic restore tool. Do not edit; entries only match by subsystem because a "
                   "cabinet carries no codec identifier. Verified hardware stays in host/devices.json.",
        "speaker_ports": [],
        "devices": devices,
    }
    (output / AUTO_TABLE).write_text(json.dumps(table, indent=2) + "\n")
    print(f"generated {len(devices)} hardware entries from {origin}")
    return len(devices)


def extract(swc, settings, output):
    output = Path(output)
    output.mkdir(parents=True, exist_ok=True)
    manifest = json.loads(Path(__file__).with_name("runtime-sha256.json").read_text())
    with tempfile.TemporaryDirectory(prefix="nahimic-runtime-", dir="/tmp") as temporary:
        work = Path(temporary)
        subprocess.run(["cabextract", "-q", "-d", str(work / "swc"), str(swc)], check=True)
        roots, vendors = [], []
        for index, (name, cabinet) in enumerate(ordered(settings_archives(settings))):
            root = work / f"vendor{index}"
            target = work / "settings.cab"
            target.write_bytes(cabinet)
            if unpack(target, root):
                roots.append(root)
                vendors.append(name)
        if not roots:
            raise ValueError("Runtime settings archive holds no vendor cabinet")
        # Shared files come from the first cabinet that carries them, device tuning is merged.
        shared, merged = roots[0], work / "merged"
        merged.mkdir()
        for relative in ("Global.nsx", "Metadata.nsx"):
            if (shared / relative).is_file():
                shutil.copyfile(shared / relative, merged / relative)
        shutil.copytree(shared / "AudioProfiles", merged / "AudioProfiles")
        (merged / "Devices").mkdir()
        for root in roots:
            for path in sorted((root / "Devices").glob("*.nsx")) if (root / "Devices").is_dir() else []:
                target = merged / "Devices" / path.name
                if not target.exists():
                    shutil.copyfile(path, target)
        for name, expected in manifest.items():
            group, relative = name.split("/", 1)
            roots_for_group = [work / "swc"] if group == "vendor" else [merged]
            source = next((root / relative for root in roots_for_group if (root / relative).is_file()), None)
            if source is None:
                raise ValueError("Runtime file is absent: " + name)
            if hashlib.sha256(source.read_bytes()).hexdigest() != expected:
                raise ValueError("Runtime checksum mismatch: " + name)
            target = output / name
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(source, target)
        unknown = [p for p in sorted((merged / "Devices").glob("*.nsx"))
                   if f"factory/Devices/{p.name}" not in manifest]
        for path in sorted((merged / "Devices").glob("*.nsx")):
            name = f"factory/Devices/{path.name}"
            if name in manifest:
                continue
            target = output / name
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(path, target)
        if unknown:
            print(f"accepted {len(unknown)} unverified tuning files: "
                  + ", ".join(p.name for p in unknown[:6])
                  + (" ..." if len(unknown) > 6 else ""))
        for name in ("Global.nsx", "Metadata.nsx"):
            if (merged / name).is_file():
                target = output / "factory" / name
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(merged / name, target)
        target = output / "factory" / "AudioProfiles"
        if not target.exists():
            shutil.copytree(merged / "AudioProfiles", target)
        device_table(merged / "Devices", output / "factory", len(vendors))


if __name__ == "__main__":
    extract(*sys.argv[1:])